### ISSUE TITLE
Java issues on mac

### ISSUE THREAD

**Issue by jejn** [jim618/multibit#665]
I'm running the latest version of MultiBit v0.5.18 on my Mac. For a long time now I haven't been able to open the application at all. When trying to run MultiBit it comes up with a message saying I have to install an older version of Java (Runtime 6) to open the application. The current version of Java is 8 and OS X doesn't even support versions older than 7 anymore. Since I can't open Multibit, I can't access my wallet. Is there any other way I can access my wallet to transfer my funds to a functioning wallet application?

**Comment by gary-rowe** [comment]
MultiBit Classic is compatible with Java 6 and higher so it should be possible to get it to launch. It may be that you simply need to install Java 6 due to the way that OS X is interpreting the JAR file.

There is a similar issue here: #492.

If you cannot get Java 6 installed you can do the following to launch MultiBit:

1. Navigate in Finder to `Applications/MultiBit HD`
1. Right click Show Package Contents
1. Navigate to `Contents/java/app`
1. Copy `multibit-hd.jar` to `~/Desktop`
1. Open Terminal and `cd ~/Desktop`
1. Launch with `java -jar multibit-hd.jar`

At this point MultiBit should start using the installed Java.

As an aside MultiBit HD (the replacement for MultiBit Classic) has an installer that packages its own JVM. If you want to try it out (it's still beta so be cautious) please visit: https://beta.multibit.org.

**Comment by itsux** [comment]
Thanks for your reply. However, I wasn't able to launch MultiBit following your instructions. It says I need to install a Java Developers Kit when running the commands you suggested in Terminal? I'm not very familiar with using Terminal and it's very frustrating having to install all kinds of different Kits/applications just to gain access to my funds. I'm just looking to access my wallet and transfer the funds but since I can't open the application I can't really do anything. The support for importing a multibit wallet to blockchain seems to be gone so it seems I'm out of options there?

As I understand it, Jave Runtime 6 does not exist anymore and is not supported by Java or OS X and therefore I'm not able to downgrade my Java version. 

I have installed MultiBit HD and it seems to be running fine but it doesn't help me much as I still can't access or import my wallet from Multibit Classic.

I had a look at the other, similar issue which seems to be the same but he got his issue resolved with a OS X upgrade. Unfortunately this hasn't been the case for me. I'm now running the lates version of OS X but had the same issue with the previous. Also, I have exactly the same issue when trying to run MultiBit on my MacBook (same OS X/MultiBit/Java version).

Although I'm no computer dummy, I'm not at all familiar or up to date with coding, terminal etc. so simply looking for a way to somehow access my wallet and transfer the funds so I can store them in a more accessible way. 

Thanks.

**Comment by gary-rowe** [comment]
Here are some [instructions on how to install Java 6 on Yosemite](http://apple.stackexchange.com/questions/153584/install-java-jre-6-next-to-jre-7-on-os-x-10-10-yosemite). 

The direct DMG link from that page is here: http://support.apple.com/downloads/DL1572/en_US/JavaForOSX2014-001.dmg.

Can you try that and then let me know how you get on? It should be a simple install process.

**Comment by itsux** [comment]
Reading through the answers on the link you provided, it seems far from a simple installation process. It involves making changes in Terminal to how OS X handles Java and suggestions being made to do it on a backup or parallel system to avoid future problems and is only recommended to people with good knowledge about what their doing.

As I mentioned before, this is very much outside my comfort zone. Is this really the only way I can access my wallet? 

I'm starting to loose faith in the whole concept of Bitcoin when insufficient support for an application can wipe out your whole wallet. It's not that I don't have backups as I have a wallet on a separate computer, but as the problem lies in the application itself and how it interacts with the operating system and the Java plugin, I have the same problem there.

Furthermore, I still have the wallet file on two computers but due to an application bug, I can't access it. Sorry for the rant but as I'm sure you can appreciate this is both frustrating and seems silly to me.

**Comment by gary-rowe** [comment]
I've always found installing Java 6 to be a simple case of downloading the DMG, clicking the installer and it's done. Can you verify that you have attempted this? In the past when OS X requested Java 6 it presented a button on the dialog to download and install it, can you also verify that this button is not present on your system?

I appreciate your concern and this is why we have moved away from a reliance on operating systems providing JVMs to providing a pre-packaged one. This is a general concern for all Java applications, not just Bitcoin wallets. The installation experience you had for MultiBit HD is indicative of how things will be moving forward.

**Comment by itsux** [comment]
When I try to open Multibit the window that opens, telling me that I need to install Java Runtime 6 to run the application, contains a button for installing Java 6. However, when clicking the button it takes me to a blank webpage (apple support). After reading a little bit about this it seems that Java 6 has now been removed or not supported anymore by OS X and Java. It seems as if it's still possible to get Java 6 back on the system by installing a JDK and then going in to the OS X code and changing the coding to allow for Java 6. This is where the potential problems can arise if not confident in what you're doing (as I understand it). I have not yet tried this as I'm worried I will mess up my system if I do. If it was merely a simple click and install I wouldn't hesitate but due to the changes made in OS X now this seems like a much more complicated task.

**Comment by gary-rowe** [comment]
Java 6 has reached end of life (this is why we're currently packaging Java 7 and later Java 8) but if your system is requesting it then you're left with 3 options in increasing order of risk:

1. Use this [Apple support page](http://support.apple.com/kb/DL1572) providing the Java 6 OS X 2014-001 which should just install without a hitch.
1. Install the latest [Oracle Java 8](http://www.oracle.com/technetwork/java/javase/downloads/index.html) which has been known to overrule the Java 6 dialog and allow normal operation (you'll need the JRE variant not the JDK)
1. Edit `Info.plist` within the `MultiBit.app` package (show package contents), look for the JVM `1.6+` and change it to `1.7+`. This may affect the signature so is not recommended unless as a last resort. 

There is [detailed technical information on the Java 6 on OS X issue](http://stackoverflow.com/questions/14806709/application-is-using-java-6-from-apple-instead-of-java-7-from-oracle-on-mac-os-x) on Stack Overflow for future readers of this issue. Unfortunately, the solution presented there is not retroactive and generally advises all application packagers to upgrade their processes. We have done this for MultiBit HD.

**Comment by gary-rowe** [comment]
Closing due to no further activity.
