### ISSUE TITLE
PGP signing key

### ISSUE THREAD

**Issue by BadGoy** [jim618/multibit#670]
Bug report
  Operating System: Win 7 Enterprise
  MultiBit Version: 0.5.18
  Steps to replicate the problem: head + wall; repeat.

multibit.org TLS Sha1:
25:79:63:94:7B:D0:80:62:F7:D0:EA:93:0B:1E:99:3B:67:F5:25:88

PGP signature verification is not working for:
dc0c2ef689507c57347c0cbed58ea90fe12617a6fb026b308e81ec2127531b7e  (checked)
multibit-0.5.18-windows-setup.exe
b8812322e670a1a46fc06d01109f7ca7479c0e8655bc167a18c59878023dbeb5  (checked)
multibit-0.5.18-windows-setup.exe.asc

Signed on 2014-04-28 04:46 with unknown certificate 0x4A71A836F57201B4D0887D600820A65823F7FB7B.
The validity of the signature cannot be verified.

I have:
299C423C672F47F4756A6BA4C1972AED79F7C572
0x23F7FB7B (a subkey of 0x79F7C572)

Using:
Kleopatra Version 2.2.0-gitac229d2 (2014-08-11)
Gpg4win Version 2.2.2

**Comment by gary-rowe** [comment]
Not sure what you're listing as being the problem here. I've just validated the signature locally as follows (forced into using a very old GPG installation so forgive older syntax):

```
gpg --verify multibit-0.5.18-windows-setup.exe.asc multibit-0.5.18-windows-setup.exe
gpg: Signature made 04/28/14 11:46:41 using RSA key ID 23F7FB7B
```

I imagine you've followed the instructions in [the digital signature article](https://multibit.org/blog/2013/07/24/how-to-check-signatures.html) which describe why in some cases you'll see a message similar to `The validity of the signature cannot be verified`. This is because, most likely, you don't trust Jim's key or any of the keys that have susequently signed it. Simply importing his key is sufficent to fix this message:

```
gpg --keyserver pgp.mit.edu --recv-keys 0x79F7C572
```

To verify the key you can [search for `0x79F7C572`](http://pgp.mit.edu:11371/pks/lookup?search=0x79F7C572) - click on Jim's credentials and look at the "sub" section at the foot of the subsequent list where you will see `0x23F7FB7B` referenced as indicated by GPG.

**Comment by BadGoy** [comment]
My mistake. The problem was that I am not familiar enough with the implementation of the "web of trust" and the necessity of myself certifying imported certificates as trusted.

Even so, by verifying the bitcoin message, I was able to determine that the sha256sums were correct.

Much thanks.

Regards,

BG

**Comment by gary-rowe** [comment]
No worries. Happy to help.
