### ISSUE TITLE
I can swear that i entered the correct password but multibit tells me "couldn't decrypt bytes"

### ISSUE THREAD

**Issue by Avuidrauxs** [jim618/multibit#673]
Please i can harbour the idea of losing my money when i'm 100% sure of the password but can't use my bitcoins. I'm willing to do anything to resolve this issue thank you

**Comment by jim618** [comment]
As I am sure you realise, there is no 'password reset' that we can do with your MultiBit wallet at our end. We never see your password (or even your wallet).

There are a couple of things you can do to try to brute-force your password which has had some success with other wallets in the past.

If you are technically minded have a read of the support note Gary has written about lost/ forgotten passwords - the section at the bottom is the relevant part:

https://multibit.org/en/help/v0.5/help_lostOrForgottenPassword.html

If this approach is not for you then I recommend you use a wallet recovery service. 'Dave's wallet recovery service' - walletrecoveryservices.com - has had some success in cracking wallets where the original password is known/ almost known. I think he checks for things like transpositions, upper/ lower case (his algo is proprietary). He does charge 20% of the bitcoin total though.
His feedback on reddit is always positive so I think he can be trusted.

Unfortunately humans and passwords just are not a brilliant mix. For instance, I occasionally type the second letter of a word as a capital e.g.  'HEllo' rather than 'Hello'. (especially if my hands are cold). Do that on both a password field and the repeast password field and it'll work but the wallet is effectively unreadble.

In MultiBit HD we have put in password recovery (from the wallet words) so hopefully this problem should be minimised going forward.

Anyhow, good luck in recovering your bitcoin

Jim

**Comment by sebastiaan321** [comment]
I have a similar problem, when I try to remove the password of one of my wallets in the MultiBit application I get "Could not decrypt bytes". When I run the following command in a terminal I get a positive result (0) meaning the password in the file is ok. The key file I got from the key-backup folder of that wallet.

`openssl enc -d -p -aes-256-cbc -a -in mykeyfile.key -out recovery.key -pass 'pass:mypassword';echo $?`

This returns 0. I tried typing and copy pasting the password but I cannot remove the password. What can be the problem?

**Comment by gary-rowe** [comment]
This looks like a duplicate/variant of #620. Closing here

**Comment by nikayang** [comment]
https://youtu.be/3hbs9Yl6cqE



For communication: SKYPE (softbtc); E-MAIL (softbtc@gmail.com)
I offer the help, to your forgotten password for BTC Wallet.dat 
Also I can give you my script, under a condition not to use him in the illegal purposes.
Donations for my script I ask 1-BTC. A half of the sum at once, a half after your success.

**Comment by Jenova55** [comment]
@sebastiaan321
did you recover your multibit wallet,
this is the issue which occurs a lot for older versions of multibit, I can recover your wallet if you still have this problem contact me at : [walletsrecoveryservice@gmail.com]

**Comment by doge2021** [comment]
> Please i can harbour the idea of losing my money when i'm 100% sure of the password but can't use my bitcoins. I'm willing to do anything to resolve this issue thank you
@sebastiaan321 @Avuidrauxs 
do you fixed it? https://btc2doge.com/multibit-hd-wallet-seed-words-not-work/
