### ISSUE TITLE
Transaction have round-status, but I sent the coin five o'clock ago

### ISSUE THREAD

**Issue by IseCrypt** [jim618/multibit#708]
Hello. Transaction have round-status, but I sent coins five o'clock ago. 
I'm reseted blockchain, but it didn't help. 

Mac OS X 10.10.2
MultiBit Classic 0.5.18

![11111](https://cloud.githubusercontent.com/assets/13238333/8571759/3f88c6ce-2591-11e5-8e65-9afd5576fcc5.png)

**Comment by jim618** [comment]
Most likely this is due to the large number of unconfirmed transactions in the Bitcoin network.
You can see the overall status at, say, https://tradeblock.com/blockchain

I just looked and there are 90,000 transactions waiting to be confirmed.
Not much to do other than be patient for the miners' to mine it I am afraid.
